# How big should the detection area be?
xLength: 24.0
yLength: 24.0
zLength: 24.0

# Should the start and completion be broadcast
# to everyone that has the RCD permission?
BroadcastRcdStartAndEnd: True
